### PR TITLE
Release version 1.2.0

### LINKED ISSUE #45: Improve cli design
As of right now, the cli is not really obvious to use. There are multiple
flags which are required, some which trigger different actions also we
have positional elements. 

This ticket was created to kick off a discussion and collect proposals 
on how to improve the cli design.

### LINKED ISSUE #82: Define some install steps/requirements
Hi all,

as the subject already mentions please create some small steps to install/setup monaco or at least some prerequisitest to install... Not everybody has go already installed.

Thanks,
Steve

### LINKED ISSUE #136: Project Path needs to be relative
Currently monaco assumes that a supplied root project path is relative off PWD.
On being given an absolute path, project_loader fails.

### PR DESCRIPTION
**Pull request by didiladi**
This commit extends the documentation for `monaco` version 1.2.0 and
sets its version. `monaco` 1.2.0 contains the following changes:

Features:

  * 4c53146 and 8611bd5 #19: Download current environment configuration (#122) 
  * dfbad92 and f54c278 Fix #45: Introduce new experimental cli design (#100)

Bugfixes:

  * fe30566 Fix #136: Handle failing to find project-root-folder path (#137)
  * 211dcbe and b74b06b Fix missing verbose flag in legacy cli (#129)

Misc changes:

  * c70ca7b Fix #82: Define some install steps/requirements (#109)

### CODE REVIEW

**Comment by patrickpichler** [comment]
The download feature documentation is still missing, if I'm not mistaken.

**Comment by didiladi** [comment]
The documentation was added in #122 (https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/4c5314667636bd34c90c1a4e0d4f00fde0826297/pkg/download/README.md). Or do you mean something else @patrickpichler?

**Comment by patrickpichler** [comment]
I was talking about documentation in the README.md, sorry.

**Comment by didiladi** [comment]
@patrickpichler and @UnseenWizzard rebased to include the latest cahnges from #137 and changed the commit msg/release notes/pr description.

**Review by UnseenWizzard — APPROVED** [review]

**Pull request merged**
