### PR TITLE
Release Version 1.0.1

### PR DESCRIPTION
**Pull request by UnseenWizzard**
Release Fix for #43: Verbose Logging isn't working

### CODE REVIEW

**Review by didiladi — CHANGES_REQUESTED** [review]
Can you also change the link in the README.md?

```
Download the latest [release](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases/tag/v1.0.0) of the tool.
```

**Comment by UnseenWizzard** [comment]
> Can you also change the link in the README.md?
> 
> ```
> Download the latest [release](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases/tag/v1.0.0) of the tool.
> ```

Actually... no :P 

I replaced it with a link to releases/latest, so we don't have to update it anymore ;)

**Review by tatomir146 — APPROVED** [review]

**Comment by didiladi** [comment]
> > Can you also change the link in the README.md?
> > ```
> > Download the latest [release](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/releases/tag/v1.0.0) of the tool.
> > ```
> 
> Actually... no :P
> 
> I replaced it with a link to releases/latest, so we don't have to update it anymore ;)

Cool, even better! :1st_place_medal:

**Review by didiladi — APPROVED** [review]

**Comment by UnseenWizzard** [comment]
it seems Github shows the tagged commit as the description of the release. 
I'll make sure to re-order the commits and have the release commit reflect the release notes tomorrow. 

We should keep this in mind for future release commits too!

**Pull request merged**
