### PR TITLE
ci: Add static code analysis of PRs

### PR DESCRIPTION
**Pull request by UnseenWizzard**
Add a PR action using the [golangci-lint](https://github.com/golangci/golangci-lint)
meta linter/linter aggregator to do analysis of the changeset.

Uses golangci-lint [Default Linters](https://golangci-lint.run/usage/linters/#enabled-by-default-linters)

And the following optional linters:
* [bodyclose](https://github.com/timakin/bodyclose)
  * checking http response.Body is closed
* [cyclop](https://github.com/bkielbasa/cyclop)
  * checking function & pkg cyclomatic complexity
* [exhaustive](https://github.com/nishanths/exhaustive)
  * checking if enum switches are exhaustive
* [godox](https://github.com/matoous/godox)
  * checking for TODO, FIXME, etc comments
* [gosec](https://github.com/securego/gosec)
  * checking for security vulnerabilities

### CODE REVIEW

**Comment by UnseenWizzard** [comment]
View this as a suggestion. 
I think static code analysis is well worth/overdue addition. 
The exact checks and when we want to do them I'd see as very open to discussion :) 

For a sample of how this action works when failing see: https://github.com/UnseenWizzard/dynatrace-monitoring-as-code/pull/2/files where the action is changed to check the full repo instead of just the changeset

**Comment by patrickpichler** [comment]
This looks awesome!

One thing, do those checks prevent a merge?

**Comment by UnseenWizzard** [comment]
> One thing, do those checks prevent a merge?

They will show as failing checks, but not prevent merging right now.
From our repo config only `Build & Test` and the >= 1 approval are required checks right now.

We can of course change that

**Comment by patrickpichler** [comment]
I would not want this to actually block merges, as sometimes a `TODO` make sense :laughing:

**Review by patrickpichler — APPROVED** [review]

**Review by didiladi — APPROVED** [review]

**Pull request merged**
