### PR TITLE
feat(api): calculated metrics for mobile, web, synthetic, service

### PR DESCRIPTION
**Pull request by didiladi**
This commit builds upon the work of @Dynatrace-Adam-Gardner and adds the
following new APIs to monaco:

  * Calculated metrics for web applications
  * Calculated metrics for mobile applications
  * Calculated metrics for synthetic tests

Additionally, it adds the new APIs to the table of token permissions in
the documentation and adds the integration test configs for the new
APIs.

For the calculated metrics of mobile apps, I temporarily defined a
mobile application (manually created) in the environment used for the
integration test. This needs to be revised, when fixing #275.

### CODE REVIEW

**Review by UnseenWizzard — APPROVED** [review]

**Comment by UnseenWizzard** [comment]
The integration test seems to have failed on this. @didiladi please don't merge yet till they re-ran

**Review by UnseenWizzard — CHANGES_REQUESTED** [review]
integration tests are failing

**Comment by UnseenWizzard** [comment]
Seems it may be unrelated to your change @didiladi, an error for test SLO configs :/ 
Can you still take a look and verify please?

https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/runs/4595645265?check_suite_focus=true
```
2021-12-21 13:57:52 INFO  Executing projects in this order: 
2021-12-21 13:57:52 INFO  	1: test-resources/integration-all-configs/project (35 configs)
2021-12-21 13:57:52 INFO  	2: test-resources/integration-all-configs/only-post (1 configs)
2021-12-21 13:57:52 INFO  Processing environment environment1...
2021-12-21 13:57:52 INFO  	Processing project test-resources/integration-all-configs/project...
2021-12-21 13:57:54 INFO  Deployment summary:
2021-12-21 13:57:54 ERROR Deployment to environment1 failed with error!
2021-12-21 13:57:54 ERROR 	Failed to create DT object My SLO_1640095072665416773AllConfigs (HTTP 400)!
    Response was: {"error":{"code":400,"message":"SLO validation failed with 1 error(s):\nEntity selector is invalid."}}, responsible config: test-resources/integration-all-configs/project/slo/slo.json
2021-12-21 13:57:54 ERROR Errors during deployment! Check log!
    all_configs_integration_test.go:44: assertion failed: 1 (statusCode int) != 0 (int)
--- FAIL: TestIntegrationAllConfigs (1.59s)
=== RUN   TestRestoreConfigsSimple
2021-12-21 13:57:54 INFO  BEGIN PREPARATION PROCESS
You are using the new CLI structure which is currently in Beta.
```

**Comment by didiladi** [comment]
> Seems it may be unrelated to your change @didiladi, an error for test SLO configs :/ Can you still take a look and verify please?
> 
> https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/runs/4595645265?check_suite_focus=true
> 
> ```
> 2021-12-21 13:57:52 INFO  Executing projects in this order: 
> 2021-12-21 13:57:52 INFO  	1: test-resources/integration-all-configs/project (35 configs)
> 2021-12-21 13:57:52 INFO  	2: test-resources/integration-all-configs/only-post (1 configs)
> 2021-12-21 13:57:52 INFO  Processing environment environment1...
> 2021-12-21 13:57:52 INFO  	Processing project test-resources/integration-all-configs/project...
> 2021-12-21 13:57:54 INFO  Deployment summary:
> 2021-12-21 13:57:54 ERROR Deployment to environment1 failed with error!
> 2021-12-21 13:57:54 ERROR 	Failed to create DT object My SLO_1640095072665416773AllConfigs (HTTP 400)!
>     Response was: {"error":{"code":400,"message":"SLO validation failed with 1 error(s):\nEntity selector is invalid."}}, responsible config: test-resources/integration-all-configs/project/slo/slo.json
> 2021-12-21 13:57:54 ERROR Errors during deployment! Check log!
>     all_configs_integration_test.go:44: assertion failed: 1 (statusCode int) != 0 (int)
> --- FAIL: TestIntegrationAllConfigs (1.59s)
> === RUN   TestRestoreConfigsSimple
> 2021-12-21 13:57:54 INFO  BEGIN PREPARATION PROCESS
> You are using the new CLI structure which is currently in Beta.
> ```

I ran the integration tests locally against out integration test environment - so I feel pretty confident that the changes work :slightly_smiling_face:  This error is a race condition between the management zone and the SLO config: #349 (its next on my list)

**Review by UnseenWizzard — APPROVED** [review]

**Comment by DavidPHirsch** [comment]
@UnseenWizzard @didiladi can this branch be updated and merged?

**Comment by DavidPHirsch** [comment]
@didiladi can we merge or are there another checks?

**Comment by UnseenWizzard** [comment]
@DavidPHirsch yes it can, so I just did :) 
generally review approval and the CI pipeline incl integration tests is the bar to pass.

**Pull request merged**
