### PR TITLE
feat: Add gitHub actions for checking commit style and generate release

### PR DESCRIPTION
**Pull request by CruzanCaramele**
notes

fixes #253

### CODE REVIEW

**Review by patrickpichler — COMMENTED** [review]
Is the `.github/workflows/conventional_commit.yml` file empty on purpose?

**Comment by CruzanCaramele** [comment]
@patrickpichler i corrected it just now , thank you :-)

**Comment by patrickpichler** [comment]
Is the format we require the commits to be in document somewhere?

**Comment by CruzanCaramele** [comment]
@patrickpichler good idea, I will add this Contributing Guide
what's your opinion ? is there a better place to put it to make it very obvious for anyone?

**Comment by patrickpichler** [comment]
Yeah the `CONTRIBUTING.md` seems like the right place for this :+1:

**Comment by UnseenWizzard** [comment]
sorry it took me forever to get to this... 
A general question to this: 
how does release-notary behave on the non-conventional commits we have in the repo so far? I assume we will have at least one release with both types of commits when this gets merged

Also as @patrickpichler mentions please make sure to document the use of conventional commits in CONTRIBUTING.md & also add a note of whether we want to use types in addition to the feat/fix of the spec (makes sense to me to use more) 

Release-notary[ seems to support a limited additional set](https://github.com/aevea/release-notary/blob/f38cd7db30d37ec0045f6d8fada151da26cae0a0/internal/text/split_sections.go#L9) of: 
* chore
* improvement
* bug
and groups the rest as other (?) - we might want to use more types still - I'll move that back to the discussion ticket

**Comment by CruzanCaramele** [comment]
@UnseenWizzard I reached out to the maintainer of release notary and informed me I can send a pull request with more Sections for him to review  if it makes sense to be added, if not then we'll need to think of another way

**Comment by patrickpichler** [comment]
@CruzanCaramele can you maybe link the issue you opened on the commit change log generator repo? 
(I assume it is an issue ^^)

**Comment by CruzanCaramele** [comment]
@patrickpichler I reached out to him directly on Twitter direct messages to ask him, I can open an issue in the repo too.
By the way I do not understand why the Test Build is failing ?

**Review by UnseenWizzard — APPROVED** [review]

**Review by didiladi — APPROVED** [review]

**Pull request merged**
