### PR TITLE
Trim Trailing Slashes

### LINKED ISSUE #102: Trim URL Trailing Slashes
**Is your feature request related to a problem? Please describe.**
Environment URLs containing trailing slashes cause the tool to fail as it'll reach out to `https://abc123.live.dynatrace.com//api`

**Describe the solution you'd like**
Trim any trailing slashes

### PR DESCRIPTION
**Pull request by Dynatrace-Adam-Gardner**
Fixes #102

### CODE REVIEW

**Review by didiladi — DISMISSED** [review]

**Comment by UnseenWizzard** [comment]
@Dynatrace-Adam-Gardner could you please rebase this on main? This seems several commits behind and has conflicts in main.go 

@patrickpichler this isn't something you already fix along with your recent CLI improvements, is it?

**Comment by patrickpichler** [comment]
@Dynatrace-Adam-Gardner please rebase on the latest `main` version.

**Comment by patrickpichler** [comment]
I noticed there is something wrong with your commits. It would be awesome if you could rebase
and drop all commits except the one introducing the change, so that we only merge those to 
master.

**Comment by Dynatrace-Adam-Gardner** [comment]
Fixing in new PR

**Pull request closed without merging**
